language: java
script: cd desapp-grupoe-backend && mvn clean verify -q
deploy:
  provider: heroku
  api_key: d75c7509-1a26-4283-ba25-3e59df710b8f
  app: adondevamos
  run:
    -java $JAVA_OPTS -jar target/dependency/jetty-runner.jar --port $PORT desapp-grupoe-backend/target/*.war
